### ISSUE TITLE
Trouble viewing minilims repositories 

### ISSUE THREAD

**Issue by boxiangliu** [madhadron/bein#22]
This might be a dumb question. 

I am following the bein tutorial (http://bbcf.epfl.ch/bein/tutorial.html). As I tried to execute the command:
'htminilims data', shell returned the following error: 

Traceback (most recent call last):
  File "/home/bliu2/anaconda/bin/htminilims", line 20, in <module>
    import bein_htminilims
  File "/home/bliu2/anaconda/lib/python2.7/site-packages/bein_htminilims/**init**.py", line 39, in <module>
    import data
ImportError: No module named data

Looking into **init**.py, there is indeed a "import data" command on line 39. Therefore I tried "pip install data", but pip says no distribution was found for the repository data. 

I am confused. Any help would be appreciated.

**Comment by signalsensefred** [comment]
data is a submodule of htminilims. If you have htminilims, you should have htminilims.data as well. You should check if there's a directory /home/bliu2/anaconda/lib/python2.7/site-packages/bein_htminilims/data on your system. If there's not, something's gone wrong in your installation.

**Comment by boxiangliu** [comment]
Thank you signalsensefred. I looked into the directory, two files, **init**.py and **init**.pyc are in this directory. I didn't find data in this directory.

I tried to reinstall bein_minilims using pip install bein_minilims and the problem persist. I wonder if there is any workaround?

**Comment by boxiangliu** [comment]
Hi signalsensefred,

I installed the developer version and it worked :). Thanks for your help.=). By the way, the warnings as I run "htminilims data", such as this one: 
  File "/home/bliu2/anaconda/lib/python2.7/logging/**init**.py", line 875, in emit
    self.flush()
makes me nervous. But the command works well regardless. 
Do you think this indicates something was wrong during installation?

**Comment by madhadron** [comment]
I'm glad it's working.

About the warnings, I really don't know. I haven't used the system in a long time. It's still in use by my old group in southern Switzerland. Are you running it on a network file system of some kind? Are there more lines to the warning than that?

If I get a little time later today I'll install it and see what it does.

On Jan 8, 2015, at 4:17 PM, Bosh Liu notifications@github.com wrote:

> Hi signalsensefred,
> 
> I installed the developer version and it worked :). Thanks for your help.=). By the way, the warnings as I run "htminilims data", such as this one: 
> File "/home/bliu2/anaconda/lib/python2.7/logging/init.py", line 875, in emit
> self.flush()
> makes me nervous. But the command works well regardless. 
> Do you think this indicates something was wrong during installation?
> 
> —
> Reply to this email directly or view it on GitHub.

Fred Ross
http://madhadron.com
